version: '3.0'
services:
  app:
    image: ruby:2.5.0
    volumes:
      - .:/app
      - bundler_data:/usr/local/bundle
    environment:
      LANG: C.UTF-8
    working_dir: /app
volumes:
  bundler_data:
